# Generated by Django 4.1.7 on 2023-02-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('insurance_info', models.TextField()),
                ('access_id', models.CharField(max_length=100)),
                ('patient_image', models.ImageField(upload_to='patients/')),
            ],
        ),
    ]
